version: "3.9"

services:
  frontend:
    container_name: frontend
    image: co-editing-frontend
    build:
      context: ./frontend/
      dockerfile: ./docker/Dockerfile
      args:
        - ENV_FILE=${ENV_FILE}
    ports:
      - "3000:3000"
    command:
      - npm
      - run
      - dev
    restart: on-failure
    volumes:
      - ./frontend/:/app/:ro
      - /app/node_modules
      - /app/.next
