version: "3.9"

services:
  backend:
    container_name: co-editing_backend
    image: co-editing-backend
    build:
      context: ./backend/
      dockerfile: ./docker/Dockerfile
    environment:
      DATABASE_HOST_NAME: co-editing_database
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "4000:8080"
    depends_on:
      - postgres
    restart: on-failure
  frontend:
    container_name: co-editing_frontend
    image: co-editing-frontend
    build:
      context: ./frontend/
      dockerfile: ./docker/Dockerfile
    ports:
      - "3000:3000"
    command: ["npm", "run", "dev", "--", "-p", "3000"]
    restart: on-failure
    volumes:
      - ./frontend/:/app/:ro
      - /app/node_modules
      - /app/.next
  postgres:
    container_name: co-editing_database
    image: co-editing-database
    restart: on-failure
    build:
      context: ./backend/
      dockerfile: ./docker/postgres.Dockerfile
    volumes:
      - test-data:/var/lib/postgressql
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5432:5432"

volumes:
  test-data:
