version: "3.9"

services:
  backend:
    container_name: co-editing_backend
    image: co-editing-backend
    build:
      context: ./backend/
      dockerfile: ./docker/Dockerfile
    ports:
      - "4000:8080"
    restart: on-failure
  frontend:
    container_name: co-editing_frontend
    image: co-editing-frontend
    build:
      context: ./frontend/
      dockerfile: ./docker/Dockerfile
    ports:
      - "3001:3001"
    command: ["npm", "run", "dev", "--", "-p", "3001"]
    restart: on-failure
    env_file: ./frontend/.env.development
    volumes:
      - ./frontend/:/app/:ro
      - /app/node_modules
      - /app/.next
